CREATE TABLE `yy_user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `id_no` varchar(10) NOT NULL COMMENT '用户编号',
  `username` varchar(30) DEFAULT NULL COMMENT '用户账号',
  `mobile` varchar(20) DEFAULT NULL COMMENT '手机号',
  `salf` char(6) DEFAULT NULL COMMENT '加密密文',
  `paypassword` char(32) DEFAULT NULL COMMENT '用户支付密码',
  `password` char(32) DEFAULT NULL COMMENT '用户密码',
  `nickname` varchar(50) NOT NULL COMMENT '昵称',
  `gender` tinyint(1) unsigned NOT NULL DEFAULT '2' COMMENT '性别：1 男 2 女 3 人妖',
  `role` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '角色：1 用户 2 美发师 3 商户',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态： 0 正常 -1 禁止',
  `birthday` int(8) DEFAULT NULL COMMENT '生日',
  `hobby` varchar(255) DEFAULT NULL COMMENT '爱好 多个爱好已,分隔',
  `job` varchar(100) DEFAULT NULL COMMENT '职业',
  `hairstyle` varchar(128) DEFAULT NULL COMMENT '发长',
  `remark` varchar(2000) DEFAULT NULL COMMENT '备注',
  `faceture` varchar(128) DEFAULT NULL COMMENT '脸型',
  `selfIntroduction` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '个人介绍',
  `shutdown` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `createtime` datetime NOT NULL COMMENT '创建时间',
  `updatetime` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `id_no_index` (`id_no`) USING BTREE,
  UNIQUE KEY `username_index` (`username`) USING BTREE,
  UNIQUE KEY `mobile_index` (`mobile`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=111111175 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='用户信息表';