<?php
return array (
	'zh-cn' =>array('name'=>'简体中文'    ,'dispname'=>'简体中文'   ,'trans'=>'zh'),
	'zh-tw' =>array('name'=>'繁体中文'    ,'dispname'=>'繁體中文'   ,'trans'=>'cht'),
	'en'    =>array('name'=>'英语'        ,'dispname'=>'English'    ,'trans'=>'en' ),
	'ko'    =>array('name'=>'韩语'        ,'dispname'=>'한국의'     ,'trans'=>'kor'),
	'ja'    =>array('name'=>'日语'        ,'dispname'=>'日本語'     ,'trans'=>'jp' ),
	'fr'    =>array('name'=>'法语'        ,'dispname'=>'Français'   ,'trans'=>'fra'),
	'de'    =>array('name'=>'德语'        ,'dispname'=>'Deutsch'    ,'trans'=>'de' ),
	'ru'    =>array('name'=>'俄语'        ,'dispname'=>'русский' ,'trans'=>'ru' ),
	'th'    =>array('name'=>'泰语'        ,'dispname'=>'ไทย'         ,'trans'=>'th' ),
	'ar'    =>array('name'=>'阿拉伯语'    ,'dispname'=>'العربية'      ,'trans'=>'ara'),
	'pl'    =>array('name'=>'波兰语'      ,'dispname'=>'polski'     ,'trans'=>'pl' ),
	'pt'    =>array('name'=>'葡萄牙语'    ,'dispname'=>'português'  ,'trans'=>'pt' ),
	'ro'    =>array('name'=>'罗马尼亚语'  ,'dispname'=>'românesc'   ,'trans'=>'rom'),
	'it'    =>array('name'=>'意大利语'    ,'dispname'=>'lingua italiana','trans'=>'it' ),
	'bg'    =>array('name'=>'保加利亚语'  ,'dispname'=>'български','trans'=>'bul'),
	'hu'    =>array('name'=>'匈牙利语'    ,'dispname'=>'magyar'     ,'trans'=>'hu' ),
	'da'    =>array('name'=>'丹麦语'      ,'dispname'=>'dansk'      ,'trans'=>'dan'),
	'cs'    =>array('name'=>'捷克语'      ,'dispname'=>'český'      ,'trans'=>'cs' ),
	'el'    =>array('name'=>'希腊语'      ,'dispname'=>'ελληνικά','trans'=>'el' ),
	'es'    =>array('name'=>'西班牙语'    ,'dispname'=>'español'    ,'trans'=>'spa'),
	'et'    =>array('name'=>'爱沙尼亚语'  ,'dispname'=>'eesti'      ,'trans'=>'est'),
	'fi'    =>array('name'=>'芬兰语'      ,'dispname'=>'suomalainen','trans'=>'fin'),
	'nl'    =>array('name'=>'荷兰语'      ,'dispname'=>'Nederlands' ,'trans'=>'nl' ),
	'sv'    =>array('name'=>'瑞典语'      ,'dispname'=>'svenska'    ,'trans'=>'swe'),
	'sl'    =>array('name'=>'斯洛文尼亚语','dispname'=>'slovenski' ,'trans'=>'slo'),
/*
//	'af'    =>array('name'=>'南非语'),
//	'af-za' =>array('name'=>'南非语'),
//	'ar-ae' =>array('name'=>'阿拉伯语(阿联酋)'),
//	'ar-bh' =>array('name'=>'阿拉伯语(巴林)'),
//	'ar-dz' =>array('name'=>'阿拉伯语(阿尔及利亚)'),
//	'ar-eg' =>array('name'=>'阿拉伯语(埃及)'),
//	'ar-iq' =>array('name'=>'阿拉伯语(伊拉克)'),
//	'ar-jo' =>array('name'=>'阿拉伯语(约旦)'),
//	'ar-kw' =>array('name'=>'阿拉伯语(科威特)'),
//	'ar-lb' =>array('name'=>'阿拉伯语(黎巴嫩)'),
//	'ar-ly' =>array('name'=>'阿拉伯语(利比亚)'),
//	'ar-ma' =>array('name'=>'阿拉伯语(摩洛哥)'),
//	'ar-om' =>array('name'=>'阿拉伯语(阿曼)'),
//	'ar-qa' =>array('name'=>'阿拉伯语(卡塔尔)'),
//	'ar-sa' =>array('name'=>'阿拉伯语(沙特阿拉伯)'),
//	'ar-sy' =>array('name'=>'阿拉伯语(叙利亚)'),
//	'ar-tn' =>array('name'=>'阿拉伯语(突尼斯)'),
//	'ar-ye' =>array('name'=>'阿拉伯语(也门)'),
	'az'    =>array('name'=>'阿塞拜疆语'),
//	'az-az' =>array('name'=>'阿塞拜疆语(拉丁文)'),
//	'az-az' =>array('name'=>'阿塞拜疆语(西里尔文)'),
	'be'    =>array('name'=>'比利时语'),
//	'be-by' =>array('name'=>'比利时语'),
//	'bg-bg' =>array('name'=>'保加利亚语'),
	'bs-ba' =>array('name'=>'波斯尼亚语'),
//	'bs-ba' =>array('name'=>'波斯尼亚语(拉丁文，波斯尼亚和黑塞哥维那)'),
	'ca'    =>array('name'=>'加泰隆语'),
//	'ca-es' =>array('name'=>'加泰隆语'),
//	'cs-cz' =>array('name'=>'捷克语'),
	'cy'    =>array('name'=>'威尔士语'),
//	'cy-gb' =>array('name'=>'威尔士语'),
//	'da-dk' =>array('name'=>'丹麦语'),
//	'de-at' =>array('name'=>'德语(奥地利)'),
//	'de-ch' =>array('name'=>'德语(瑞士)'),
//	'de-de' =>array('name'=>'德语(德国)'),
//	'de-li' =>array('name'=>'德语(列支敦士登)'),
//	'de-lu' =>array('name'=>'德语(卢森堡)'),
	'dv'    =>array('name'=>'第维埃语'),
//	'dv-mv' =>array('name'=>'第维埃语'),
//	'el-gr' =>array('name'=>'希腊语'),
//	'en-au' =>array('name'=>'英语(澳大利亚)'),
//	'en-bz' =>array('name'=>'英语(伯利兹)'),
//	'en-ca' =>array('name'=>'英语(加拿大)'),
//	'en-cb' =>array('name'=>'英语(加勒比海)'),
//	'en-gb' =>array('name'=>'英语(英国)'),
//	'en-ie' =>array('name'=>'英语(爱尔兰)'),
//	'en-jm' =>array('name'=>'英语(牙买加)'),
//	'en-nz' =>array('name'=>'英语(新西兰)'),
//	'en-ph' =>array('name'=>'英语(菲律宾)'),
//	'en-tt' =>array('name'=>'英语(特立尼达)'),
//	'en-us' =>array('name'=>'英语'),
//	'en-za' =>array('name'=>'英语(南非)'),
//	'en-zw' =>array('name'=>'英语(津巴布韦)'),
//	'eo'    =>array('name'=>'世界语'),
//	'es-ar' =>array('name'=>'西班牙语(阿根廷)'),
//	'es-bo' =>array('name'=>'西班牙语(玻利维亚)'),
//	'es-cl' =>array('name'=>'西班牙语(智利)'),
//	'es-co' =>array('name'=>'西班牙语(哥伦比亚)'),
//	'es-cr' =>array('name'=>'西班牙语(哥斯达黎加)'),
//	'es-do' =>array('name'=>'西班牙语(多米尼加共和国)'),
//	'es-ec' =>array('name'=>'西班牙语(厄瓜多尔)'),
//	'es-es' =>array('name'=>'西班牙语(传统)'),
//	'es-es' =>array('name'=>'西班牙语(国际)'),
//	'es-gt' =>array('name'=>'西班牙语(危地马拉)'),
//	'es-hn' =>array('name'=>'西班牙语(洪都拉斯)'),
//	'es-mx' =>array('name'=>'西班牙语(墨西哥)'),
//	'es-ni' =>array('name'=>'西班牙语(尼加拉瓜)'),
//	'es-pa' =>array('name'=>'西班牙语(巴拿马)'),
//	'es-pe' =>array('name'=>'西班牙语(秘鲁)'),
//	'es-pr' =>array('name'=>'西班牙语(波多黎各(美))'),
//	'es-py' =>array('name'=>'西班牙语(巴拉圭)'),
//	'es-sv' =>array('name'=>'西班牙语(萨尔瓦多)'),
//	'es-uy' =>array('name'=>'西班牙语(乌拉圭)'),
//	'es-ve' =>array('name'=>'西班牙语(委内瑞拉)'),
//	'et-ee' =>array('name'=>'爱沙尼亚语'),
	'eu'    =>array('name'=>'巴士克语'),
//	'eu-es' =>array('name'=>'巴士克语'),
	'fa'    =>array('name'=>'法斯语'),
//	'fa-ir' =>array('name'=>'法斯语'),
//	'fi-fi' =>array('name'=>'芬兰语'),
	'fo'    =>array('name'=>'法罗语'),
//	'fo-fo' =>array('name'=>'法罗语'),
//	'fr-be' =>array('name'=>'法语(比利时)'),
//	'fr-ca' =>array('name'=>'法语(加拿大)'),
//	'fr-ch' =>array('name'=>'法语(瑞士)'),
//	'fr-fr' =>array('name'=>'法语(法国)'),
//	'fr-lu' =>array('name'=>'法语(卢森堡)'),
//	'fr-mc' =>array('name'=>'法语(摩纳哥)'),
	'gl'    =>array('name'=>'加里西亚语'),
//	'gl-es' =>array('name'=>'加里西亚语'),
	'gu'    =>array('name'=>'古吉拉特语'),
//	'gu-in' =>array('name'=>'古吉拉特语'),
	'he'    =>array('name'=>'希伯来语'),
//	'he-il' =>array('name'=>'希伯来语'),
	'hi'    =>array('name'=>'印地语'),
//	'hi-in' =>array('name'=>'印地语'),
	'hr'    =>array('name'=>'克罗地亚语'),
//	'hr-ba' =>array('name'=>'克罗地亚语(波斯尼亚和黑塞哥维那)'),
//	'hr-hr' =>array('name'=>'克罗地亚语'),
//	'hu-hu' =>array('name'=>'匈牙利语'),
	'hy'    =>array('name'=>'亚美尼亚语'),
//	'hy-am' =>array('name'=>'亚美尼亚语'),
	'id'    =>array('name'=>'印度尼西亚语'),
//	'id-id' =>array('name'=>'印度尼西亚语'),
	'is'    =>array('name'=>'冰岛语'),
//	'is-is' =>array('name'=>'冰岛语'),
//	'it-ch' =>array('name'=>'意大利语(瑞士)'),
//	'it-it' =>array('name'=>'意大利语(意大利)'),
//	'ja-jp' =>array('name'=>'日语'),
	'ka'    =>array('name'=>'格鲁吉亚语'),
//	'ka-ge' =>array('name'=>'格鲁吉亚语'),
	'kk'    =>array('name'=>'哈萨克语'),
//	'kk-kz' =>array('name'=>'哈萨克语'),
	'kn'    =>array('name'=>'卡纳拉语'),
//	'kn-in' =>array('name'=>'卡纳拉语'),
//	'ko-kr' =>array('name'=>'朝鲜语'),
	'kok'   =>array('name'=>'孔卡尼语'),
//	'kok-in'=>array('name'=>'孔卡尼语'),
	'ky'    =>array('name'=>'吉尔吉斯语'),
//	'ky-kg' =>array('name'=>'吉尔吉斯语(西里尔文)'),
	'lt'    =>array('name'=>'立陶宛语'),
//	'lt-lt' =>array('name'=>'立陶宛语'),
	'lv'    =>array('name'=>'拉脱维亚语'),
//	'lv-lv' =>array('name'=>'拉脱维亚语'),
	'mi'    =>array('name'=>'毛利语'),
//	'mi-nz' =>array('name'=>'毛利语'),
	'mk'    =>array('name'=>'马其顿语'),
//	'mk-mk' =>array('name'=>'马其顿语(fyrom)'),
	'mn'    =>array('name'=>'蒙古语'),
//	'mn-mn' =>array('name'=>'蒙古语(西里尔文)'),
	'mr'    =>array('name'=>'马拉地语'),
//	'mr-in' =>array('name'=>'马拉地语'),
	'ms'    =>array('name'=>'马来语'),
//	'ms-bn' =>array('name'=>'马来语(文莱达鲁萨兰)'),
//	'ms-my' =>array('name'=>'马来语(马来西亚)'),
	'mt'    =>array('name'=>'马耳他语'),
//	'mt-mt' =>array('name'=>'马耳他语'),
	'nb'    =>array('name'=>'挪威语'),
//	'nb'    =>array('name'=>'挪威语(伯克梅尔)'),
//	'nb-no' =>array('name'=>'挪威语(伯克梅尔)(挪威)'),
//	'nn-no' =>array('name'=>'挪威语(尼诺斯克)(挪威)'),
//	'nl-be' =>array('name'=>'荷兰语(比利时)'),
//	'nl-nl' =>array('name'=>'荷兰语(荷兰)'),
	'ns'    =>array('name'=>'北梭托语'),
//	'ns-za' =>array('name'=>'北梭托语'),
	'pa'    =>array('name'=>'旁遮普语'),
//	'pa-in' =>array('name'=>'旁遮普语'),
//	'pl-pl' =>array('name'=>'波兰语'),
//	'pt-br' =>array('name'=>'葡萄牙语(巴西)'),
//	'pt-pt' =>array('name'=>'葡萄牙语(葡萄牙)'),
	'qu'    =>array('name'=>'克丘亚语'),
//	'qu-bo' =>array('name'=>'克丘亚语(玻利维亚)'),
//	'qu-ec' =>array('name'=>'克丘亚语(厄瓜多尔)'),
//	'qu-pe' =>array('name'=>'克丘亚语(秘鲁)'),
//	'ro-ro' =>array('name'=>'罗马尼亚语'),
//	'ru-ru' =>array('name'=>'俄语'),
	'sa'    =>array('name'=>'梵文'),
//	'sa-in' =>array('name'=>'梵文'),
	'se'    =>array('name'=>'北萨摩斯语'),
//	'se-fi' =>array('name'=>'北萨摩斯语(芬兰)'),
//	'se-fi' =>array('name'=>'斯科特萨摩斯语(芬兰)'),
//	'se-fi' =>array('name'=>'伊那里萨摩斯语(芬兰)'),
//	'se-no' =>array('name'=>'北萨摩斯语(挪威)'),
//	'se-no' =>array('name'=>'律勒欧萨摩斯语(挪威)'),
//	'se-no' =>array('name'=>'南萨摩斯语(挪威)'),
//	'se-se' =>array('name'=>'北萨摩斯语(瑞典)'),
//	'se-se' =>array('name'=>'律勒欧萨摩斯语(瑞典)'),
//	'se-se' =>array('name'=>'南萨摩斯语(瑞典)'),
	'sk'    =>array('name'=>'斯洛伐克语'),
//	'sk-sk' =>array('name'=>'斯洛伐克语'),
//	'sl-si' =>array('name'=>'斯洛文尼亚语'),
	'sq'    =>array('name'=>'阿尔巴尼亚语'),
//	'sq-al' =>array('name'=>'阿尔巴尼亚语'),
	'sr'    =>array('name'=>'塞尔维亚语'),
//	'sr-ba' =>array('name'=>'塞尔维亚语(拉丁文，波斯尼亚和黑塞哥维那)'),
//	'sr-ba' =>array('name'=>'塞尔维亚语(西里尔文，波斯尼亚和黑塞哥维那)'),
//	'sr-sp' =>array('name'=>'塞尔维亚语(拉丁)'),
//	'sr-sp' =>array('name'=>'塞尔维亚语(西里尔文)'),
//	'sv-fi' =>array('name'=>'瑞典语(芬兰)'),
//	'sv-se' =>array('name'=>'瑞典语'),
	'sw'    =>array('name'=>'斯瓦希里语'),
//	'sw-ke' =>array('name'=>'斯瓦希里语'),
	'syr'   =>array('name'=>'叙利亚语'),
//	'syr-sy'=>array('name'=>'叙利亚语'),
	'ta'    =>array('name'=>'泰米尔语'),
//	'ta-in' =>array('name'=>'泰米尔语'),
	'te'    =>array('name'=>'泰卢固语'),
//	'te-in' =>array('name'=>'泰卢固语'),
//	'th-th' =>array('name'=>'泰语'),
	'tl'    =>array('name'=>'塔加路语'),
//	'tl-ph' =>array('name'=>'塔加路语(菲律宾)'),
	'tn'    =>array('name'=>'茨瓦纳语'),
//	'tn-za' =>array('name'=>'茨瓦纳语'),
	'tr'    =>array('name'=>'土耳其语'),
//	'tr-tr' =>array('name'=>'土耳其语'),
	'ts'    =>array('name'=>'宗加语'),
	'tt'    =>array('name'=>'鞑靼语'),
//	'tt-ru' =>array('name'=>'鞑靼语'),
	'uk'    =>array('name'=>'乌克兰语'),
//	'uk-ua' =>array('name'=>'乌克兰语'),
	'ur'    =>array('name'=>'乌都语'),
//	'ur-pk' =>array('name'=>'乌都语'),
	'uz'    =>array('name'=>'乌兹别克语'),
//	'uz-uz' =>array('name'=>'乌兹别克语(拉丁文)'),
//	'uz-uz' =>array('name'=>'乌兹别克语(西里尔文)'),
	'vi'    =>array('name'=>'越南语'),
//	'vi-vn' =>array('name'=>'越南语'),
	'xh'    =>array('name'=>'班图语'),
//	'xh-za' =>array('name'=>'班图语'),
//	'zh'    =>array('name'=>'中文'),
	
//	'zh-hk' =>array('name'=>'中文(香港)'),
//	'zh-mo' =>array('name'=>'中文(澳门)'),
//	'zh-sg' =>array('name'=>'中文(新加坡)'),
	'zu'    =>array('name'=>'祖鲁语'),
//	'zu-za' =>array('name'=>'祖鲁语'),
*/
);
?>